//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HTMLParser.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="HTMLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IHTMLParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlDocument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlDocument([NotNull] HTMLParser.HtmlDocumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.scriptletOrSeaWs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptletOrSeaWs([NotNull] HTMLParser.ScriptletOrSeaWsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlElements([NotNull] HTMLParser.HtmlElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlElement([NotNull] HTMLParser.HtmlElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlContent([NotNull] HTMLParser.HtmlContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlAttribute([NotNull] HTMLParser.HtmlAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlChardata"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlChardata([NotNull] HTMLParser.HtmlChardataContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlMisc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlMisc([NotNull] HTMLParser.HtmlMiscContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.htmlComment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHtmlComment([NotNull] HTMLParser.HtmlCommentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] HTMLParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="HTMLParser.style"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStyle([NotNull] HTMLParser.StyleContext context);
}
